require 'uri'
require 'open-uri'
require 'nokogiri'
require 'set'

require_relative 'scraper'
require_relative 'product_data'
require_relative 'comparator'
require_relative 'products_match'
require_relative 'match_word'
require_relative 'matching_manager'